apiVersion: apps/v1
kind: Deployment
metadata: 
  name: php
  labels: 
    app: php
spec:
  replicas: 6
  selector:
    matchLabels: 
      app: php
  template:
    metadata:
      labels:
        app: php  
    spec:
      containers:
      - name: php
        image: matheusgomesa/projeto-dio-backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: php